version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: shopster-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shopster
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - shopster-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  shopster-postgres-data:
